package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88-dev

import (
	"context"
	"encoding/base64"
	"fmt"

	"github.com/magendooro/magento2-cart-graphql-go/graph/model"
)

// CreateEmptyCart is the resolver for the createEmptyCart field.
func (r *mutationResolver) CreateEmptyCart(ctx context.Context, input *model.CreateEmptyCartInput) (*string, error) {
	maskedID, err := r.CartService.CreateEmptyCart(ctx)
	if err != nil {
		return nil, err
	}
	return &maskedID, nil
}

// CreateGuestCart is the resolver for the createGuestCart field.
func (r *mutationResolver) CreateGuestCart(ctx context.Context, input *model.CreateGuestCartInput) (*model.CreateGuestCartOutput, error) {
	maskedID, err := r.CartService.CreateEmptyCart(ctx)
	if err != nil {
		return nil, err
	}
	cart, err := r.CartService.GetCart(ctx, maskedID)
	if err != nil {
		return nil, err
	}
	return &model.CreateGuestCartOutput{Cart: cart}, nil
}

// AddProductsToCart is the resolver for the addProductsToCart field.
func (r *mutationResolver) AddProductsToCart(ctx context.Context, cartID string, cartItems []*model.CartItemInput) (*model.AddProductsToCartOutput, error) {
	return r.CartService.AddProducts(ctx, cartID, cartItems)
}

// AddSimpleProductsToCart is the resolver for the addSimpleProductsToCart field.
func (r *mutationResolver) AddSimpleProductsToCart(ctx context.Context, input *model.AddSimpleProductsToCartInput) (*model.AddSimpleProductsToCartOutput, error) {
	if input == nil {
		return nil, fmt.Errorf("input required")
	}
	items := make([]*model.CartItemInput, len(input.CartItems))
	for i, ci := range input.CartItems {
		items[i] = ci.Data
	}
	out, err := r.CartService.AddProducts(ctx, input.CartID, items)
	if err != nil {
		return nil, err
	}
	return &model.AddSimpleProductsToCartOutput{Cart: out.Cart}, nil
}

// AddVirtualProductsToCart is the resolver for the addVirtualProductsToCart field.
func (r *mutationResolver) AddVirtualProductsToCart(ctx context.Context, input *model.AddVirtualProductsToCartInput) (*model.AddVirtualProductsToCartOutput, error) {
	if input == nil {
		return nil, fmt.Errorf("input required")
	}
	items := make([]*model.CartItemInput, len(input.CartItems))
	for i, ci := range input.CartItems {
		items[i] = ci.Data
	}
	out, err := r.CartService.AddProducts(ctx, input.CartID, items)
	if err != nil {
		return nil, err
	}
	return &model.AddVirtualProductsToCartOutput{Cart: out.Cart}, nil
}

// AddConfigurableProductsToCart is the resolver for the addConfigurableProductsToCart field.
func (r *mutationResolver) AddConfigurableProductsToCart(ctx context.Context, input *model.AddConfigurableProductsToCartInput) (*model.AddConfigurableProductsToCartOutput, error) {
	if input == nil {
		return nil, fmt.Errorf("input required")
	}
	items := make([]*model.CartItemInput, len(input.CartItems))
	for i, ci := range input.CartItems {
		item := *ci.Data
		// parent_sku on the wrapper overrides the one in data
		if ci.ParentSku != nil {
			item.ParentSku = ci.ParentSku
		}
		items[i] = &item
	}
	out, err := r.CartService.AddProducts(ctx, input.CartID, items)
	if err != nil {
		return nil, err
	}
	return &model.AddConfigurableProductsToCartOutput{Cart: out.Cart}, nil
}

// AddBundleProductsToCart is the resolver for the addBundleProductsToCart field.
func (r *mutationResolver) AddBundleProductsToCart(ctx context.Context, input *model.AddBundleProductsToCartInput) (*model.AddBundleProductsToCartOutput, error) {
	if input == nil {
		return nil, fmt.Errorf("input required")
	}
	items := make([]*model.CartItemInput, len(input.CartItems))
	for i, ci := range input.CartItems {
		item := *ci.Data
		// Convert BundleOptionInput {id, quantity, value:[selectionID...]} to selected_options UIDs.
		// UID format: base64("bundle/<optionID>/<selectionID>")
		for _, bo := range ci.BundleOptions {
			for _, selIDStr := range bo.Value {
				uid := base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("bundle/%d/%s", bo.ID, selIDStr)))
				item.SelectedOptions = append(item.SelectedOptions, uid)
			}
		}
		items[i] = &item
	}
	out, err := r.CartService.AddProducts(ctx, input.CartID, items)
	if err != nil {
		return nil, err
	}
	return &model.AddBundleProductsToCartOutput{Cart: out.Cart}, nil
}

// UpdateCartItems is the resolver for the updateCartItems field.
func (r *mutationResolver) UpdateCartItems(ctx context.Context, input *model.UpdateCartItemsInput) (*model.UpdateCartItemsOutput, error) {
	cart, err := r.CartService.UpdateItems(ctx, input.CartID, input.CartItems)
	if err != nil {
		return nil, err
	}
	return &model.UpdateCartItemsOutput{Cart: cart}, nil
}

// RemoveItemFromCart is the resolver for the removeItemFromCart field.
func (r *mutationResolver) RemoveItemFromCart(ctx context.Context, input *model.RemoveItemFromCartInput) (*model.RemoveItemFromCartOutput, error) {
	cart, err := r.CartService.RemoveItem(ctx, input.CartID, input.CartItemUID)
	if err != nil {
		return nil, err
	}
	return &model.RemoveItemFromCartOutput{Cart: cart}, nil
}

// SetShippingAddressesOnCart is the resolver for the setShippingAddressesOnCart field.
func (r *mutationResolver) SetShippingAddressesOnCart(ctx context.Context, input *model.SetShippingAddressesOnCartInput) (*model.SetShippingAddressesOnCartOutput, error) {
	cart, err := r.CartService.SetShippingAddresses(ctx, input.CartID, input.ShippingAddresses)
	if err != nil {
		return nil, err
	}
	return &model.SetShippingAddressesOnCartOutput{Cart: cart}, nil
}

// SetBillingAddressOnCart is the resolver for the setBillingAddressOnCart field.
func (r *mutationResolver) SetBillingAddressOnCart(ctx context.Context, input *model.SetBillingAddressOnCartInput) (*model.SetBillingAddressOnCartOutput, error) {
	cart, err := r.CartService.SetBillingAddress(ctx, input.CartID, input.BillingAddress)
	if err != nil {
		return nil, err
	}
	return &model.SetBillingAddressOnCartOutput{Cart: cart}, nil
}

// SetShippingMethodsOnCart is the resolver for the setShippingMethodsOnCart field.
func (r *mutationResolver) SetShippingMethodsOnCart(ctx context.Context, input *model.SetShippingMethodsOnCartInput) (*model.SetShippingMethodsOnCartOutput, error) {
	cart, err := r.CartService.SetShippingMethods(ctx, input.CartID, input.ShippingMethods)
	if err != nil {
		return nil, err
	}
	return &model.SetShippingMethodsOnCartOutput{Cart: cart}, nil
}

// SetPaymentMethodOnCart is the resolver for the setPaymentMethodOnCart field.
func (r *mutationResolver) SetPaymentMethodOnCart(ctx context.Context, input *model.SetPaymentMethodOnCartInput) (*model.SetPaymentMethodOnCartOutput, error) {
	cart, err := r.CartService.SetPaymentMethod(ctx, input.CartID, input.PaymentMethod.Code)
	if err != nil {
		return nil, err
	}
	return &model.SetPaymentMethodOnCartOutput{Cart: cart}, nil
}

// SetGuestEmailOnCart is the resolver for the setGuestEmailOnCart field.
func (r *mutationResolver) SetGuestEmailOnCart(ctx context.Context, input *model.SetGuestEmailOnCartInput) (*model.SetGuestEmailOnCartOutput, error) {
	cart, err := r.CartService.SetGuestEmail(ctx, input.CartID, input.Email)
	if err != nil {
		return nil, err
	}
	return &model.SetGuestEmailOnCartOutput{Cart: cart}, nil
}

// PlaceOrder is the resolver for the placeOrder field.
func (r *mutationResolver) PlaceOrder(ctx context.Context, input *model.PlaceOrderInput) (*model.PlaceOrderOutput, error) {
	return r.CartService.PlaceOrder(ctx, input.CartID)
}

// ApplyCouponToCart is the resolver for the applyCouponToCart field.
func (r *mutationResolver) ApplyCouponToCart(ctx context.Context, input *model.ApplyCouponToCartInput) (*model.ApplyCouponToCartOutput, error) {
	cart, err := r.CartService.ApplyCoupon(ctx, input.CartID, input.CouponCode)
	if err != nil {
		return nil, err
	}
	return &model.ApplyCouponToCartOutput{Cart: cart}, nil
}

// RemoveCouponFromCart is the resolver for the removeCouponFromCart field.
func (r *mutationResolver) RemoveCouponFromCart(ctx context.Context, input *model.RemoveCouponFromCartInput) (*model.RemoveCouponFromCartOutput, error) {
	cart, err := r.CartService.RemoveCoupon(ctx, input.CartID)
	if err != nil {
		return nil, err
	}
	return &model.RemoveCouponFromCartOutput{Cart: cart}, nil
}

// MergeCarts is the resolver for the mergeCarts field.
func (r *mutationResolver) MergeCarts(ctx context.Context, sourceCartID string, destinationCartID *string) (*model.Cart, error) {
	return r.CartService.MergeCarts(ctx, sourceCartID, destinationCartID)
}

// AssignCustomerToGuestCart is the resolver for the assignCustomerToGuestCart field.
func (r *mutationResolver) AssignCustomerToGuestCart(ctx context.Context, cartID string) (*model.Cart, error) {
	return r.CartService.AssignCustomerToGuestCart(ctx, cartID)
}

// EstimateShippingMethods is the resolver for the estimateShippingMethods field.
func (r *mutationResolver) EstimateShippingMethods(ctx context.Context, input model.EstimateShippingMethodsInput) ([]*model.AvailableShippingMethod, error) {
	return r.CartService.EstimateShippingMethods(ctx, input)
}

// EstimateTotals is the resolver for the estimateTotals field.
func (r *mutationResolver) EstimateTotals(ctx context.Context, input model.EstimateTotalsInput) (*model.EstimateTotalsOutput, error) {
	return r.CartService.EstimateTotals(ctx, input)
}

// ReorderItems is the resolver for the reorderItems field.
func (r *mutationResolver) ReorderItems(ctx context.Context, orderNumber string) (*model.ReorderItemsOutput, error) {
	return r.CartService.ReorderItems(ctx, orderNumber)
}

// Cart is the resolver for the cart field.
func (r *queryResolver) Cart(ctx context.Context, cartID string) (*model.Cart, error) {
	return r.CartService.GetCart(ctx, cartID)
}

// CustomerCart is the resolver for the customerCart field.
func (r *queryResolver) CustomerCart(ctx context.Context) (*model.Cart, error) {
	return r.CartService.GetCustomerCart(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
