// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CartItemInterface interface {
	IsCartItemInterface()
	GetUID() string
	GetQuantity() float64
	GetPrices() *CartItemPrices
	GetProduct() *CartItemProduct
	GetErrors() []*CartItemError
}

type AddBundleProductsToCartInput struct {
	CartID    string                        `json:"cart_id"`
	CartItems []*BundleProductCartItemInput `json:"cart_items"`
}

type AddBundleProductsToCartOutput struct {
	Cart *Cart `json:"cart"`
}

type AddConfigurableProductsToCartInput struct {
	CartID    string                              `json:"cart_id"`
	CartItems []*ConfigurableProductCartItemInput `json:"cart_items"`
}

type AddConfigurableProductsToCartOutput struct {
	Cart *Cart `json:"cart"`
}

type AddProductsToCartOutput struct {
	Cart       *Cart                 `json:"cart"`
	UserErrors []*CartUserInputError `json:"user_errors"`
}

type AddSimpleProductsToCartInput struct {
	CartID    string                        `json:"cart_id"`
	CartItems []*SimpleProductCartItemInput `json:"cart_items"`
}

type AddSimpleProductsToCartOutput struct {
	Cart *Cart `json:"cart"`
}

type AddVirtualProductsToCartInput struct {
	CartID    string                         `json:"cart_id"`
	CartItems []*VirtualProductCartItemInput `json:"cart_items"`
}

type AddVirtualProductsToCartOutput struct {
	Cart *Cart `json:"cart"`
}

type AppliedCoupon struct {
	Code string `json:"code"`
}

type ApplyCouponToCartInput struct {
	CartID     string `json:"cart_id"`
	CouponCode string `json:"coupon_code"`
}

type ApplyCouponToCartOutput struct {
	Cart *Cart `json:"cart"`
}

type AvailablePaymentMethod struct {
	Code  string `json:"code"`
	Title string `json:"title"`
}

type AvailableShippingMethod struct {
	CarrierCode  string  `json:"carrier_code"`
	CarrierTitle string  `json:"carrier_title"`
	MethodCode   string  `json:"method_code"`
	MethodTitle  string  `json:"method_title"`
	Amount       *Money  `json:"amount"`
	PriceExclTax *Money  `json:"price_excl_tax"`
	PriceInclTax *Money  `json:"price_incl_tax"`
	Available    bool    `json:"available"`
	ErrorMessage *string `json:"error_message,omitempty"`
}

type BillingAddressInput struct {
	Address           *CartAddressInput `json:"address,omitempty"`
	CustomerAddressID *int              `json:"customer_address_id,omitempty"`
	SameAsShipping    *bool             `json:"same_as_shipping,omitempty"`
}

type BillingCartAddress struct {
	Firstname string              `json:"firstname"`
	Lastname  string              `json:"lastname"`
	Street    []*string           `json:"street"`
	City      string              `json:"city"`
	Region    *CartAddressRegion  `json:"region,omitempty"`
	Postcode  *string             `json:"postcode,omitempty"`
	Country   *CartAddressCountry `json:"country"`
	Telephone *string             `json:"telephone,omitempty"`
	Company   *string             `json:"company,omitempty"`
}

type BundleCartItem struct {
	UID                 string                        `json:"uid"`
	Quantity            float64                       `json:"quantity"`
	Prices              *CartItemPrices               `json:"prices,omitempty"`
	Product             *CartItemProduct              `json:"product"`
	Errors              []*CartItemError              `json:"errors,omitempty"`
	BundleOptions       []*SelectedBundleOption       `json:"bundle_options"`
	CustomizableOptions []*SelectedCustomizableOption `json:"customizable_options"`
}

func (BundleCartItem) IsCartItemInterface()              {}
func (this BundleCartItem) GetUID() string               { return this.UID }
func (this BundleCartItem) GetQuantity() float64         { return this.Quantity }
func (this BundleCartItem) GetPrices() *CartItemPrices   { return this.Prices }
func (this BundleCartItem) GetProduct() *CartItemProduct { return this.Product }
func (this BundleCartItem) GetErrors() []*CartItemError {
	if this.Errors == nil {
		return nil
	}
	interfaceSlice := make([]*CartItemError, 0, len(this.Errors))
	for _, concrete := range this.Errors {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}

type BundleOptionInput struct {
	ID       int      `json:"id"`
	Quantity float64  `json:"quantity"`
	Value    []string `json:"value"`
}

type BundleProductCartItemInput struct {
	Data                *CartItemInput             `json:"data"`
	BundleOptions       []*BundleOptionInput       `json:"bundle_options"`
	CustomizableOptions []*CustomizableOptionInput `json:"customizable_options,omitempty"`
}

type Cart struct {
	ID                      string                    `json:"id"`
	Items                   []CartItemInterface       `json:"items,omitempty"`
	ItemsV2                 *CartItems                `json:"itemsV2,omitempty"`
	TotalQuantity           float64                   `json:"total_quantity"`
	IsVirtual               bool                      `json:"is_virtual"`
	Email                   *string                   `json:"email,omitempty"`
	AppliedCoupons          []*AppliedCoupon          `json:"applied_coupons,omitempty"`
	ShippingAddresses       []*ShippingCartAddress    `json:"shipping_addresses"`
	BillingAddress          *BillingCartAddress       `json:"billing_address,omitempty"`
	AvailablePaymentMethods []*AvailablePaymentMethod `json:"available_payment_methods,omitempty"`
	SelectedPaymentMethod   *SelectedPaymentMethod    `json:"selected_payment_method,omitempty"`
	Prices                  *CartPrices               `json:"prices,omitempty"`
}

type CartAddressCountry struct {
	Code  string `json:"code"`
	Label string `json:"label"`
}

type CartAddressInput struct {
	Firstname   string   `json:"firstname"`
	Lastname    string   `json:"lastname"`
	Company     *string  `json:"company,omitempty"`
	Street      []string `json:"street"`
	City        string   `json:"city"`
	Region      *string  `json:"region,omitempty"`
	RegionID    *int     `json:"region_id,omitempty"`
	Postcode    *string  `json:"postcode,omitempty"`
	CountryCode string   `json:"country_code"`
	Telephone   *string  `json:"telephone,omitempty"`
}

type CartAddressRegion struct {
	Code     *string `json:"code,omitempty"`
	Label    *string `json:"label,omitempty"`
	RegionID *int    `json:"region_id,omitempty"`
}

type CartItemError struct {
	Code    CartItemErrorType `json:"code"`
	Message string            `json:"message"`
}

type CartItemInput struct {
	Sku             string                `json:"sku"`
	Quantity        float64               `json:"quantity"`
	ParentSku       *string               `json:"parent_sku,omitempty"`
	SelectedOptions []string              `json:"selected_options,omitempty"`
	EnteredOptions  []*EnteredOptionInput `json:"entered_options,omitempty"`
}

type CartItemPrices struct {
	Price                *Money      `json:"price"`
	RowTotal             *Money      `json:"row_total"`
	RowTotalIncludingTax *Money      `json:"row_total_including_tax"`
	TotalItemDiscount    *Money      `json:"total_item_discount,omitempty"`
	Discounts            []*Discount `json:"discounts,omitempty"`
}

type CartItemProduct struct {
	Sku       string                `json:"sku"`
	Name      *string               `json:"name,omitempty"`
	URLKey    *string               `json:"url_key,omitempty"`
	Thumbnail *CartItemProductImage `json:"thumbnail,omitempty"`
}

type CartItemProductImage struct {
	URL   *string `json:"url,omitempty"`
	Label *string `json:"label,omitempty"`
}

type CartItemSelectedOptionValuePrice struct {
	Type  PriceTypeEnum `json:"type"`
	Units string        `json:"units"`
	Value float64       `json:"value"`
}

type CartItemUpdateInput struct {
	CartItemUID string  `json:"cart_item_uid"`
	Quantity    float64 `json:"quantity"`
}

type CartItems struct {
	Items      []CartItemInterface   `json:"items"`
	PageInfo   *SearchResultPageInfo `json:"page_info"`
	TotalCount int                   `json:"total_count"`
}

type CartPrices struct {
	GrandTotal                       *Money         `json:"grand_total,omitempty"`
	SubtotalIncludingTax             *Money         `json:"subtotal_including_tax,omitempty"`
	SubtotalExcludingTax             *Money         `json:"subtotal_excluding_tax,omitempty"`
	SubtotalWithDiscountExcludingTax *Money         `json:"subtotal_with_discount_excluding_tax,omitempty"`
	AppliedTaxes                     []*CartTaxItem `json:"applied_taxes,omitempty"`
	Discounts                        []*Discount    `json:"discounts,omitempty"`
}

type CartTaxItem struct {
	Amount *Money `json:"amount"`
	Label  string `json:"label"`
}

type CartUserInputError struct {
	Code    CartUserInputErrorType `json:"code"`
	Message string                 `json:"message"`
}

// A single Terms and Conditions agreement that must be accepted before checkout.
type CheckoutAgreement struct {
	AgreementID   int                   `json:"agreement_id"`
	Name          string                `json:"name"`
	Content       string                `json:"content"`
	ContentHeight *string               `json:"content_height,omitempty"`
	CheckboxText  string                `json:"checkbox_text"`
	IsHTML        bool                  `json:"is_html"`
	Mode          CheckoutAgreementMode `json:"mode"`
}

type CheckoutUserInputError struct {
	Code    CheckoutUserInputErrorCodes `json:"code"`
	Message string                      `json:"message"`
	Path    []string                    `json:"path"`
}

type ConfigurableCartItem struct {
	UID                 string                        `json:"uid"`
	Quantity            float64                       `json:"quantity"`
	Prices              *CartItemPrices               `json:"prices,omitempty"`
	Product             *CartItemProduct              `json:"product"`
	Errors              []*CartItemError              `json:"errors,omitempty"`
	ConfigurableOptions []*SelectedConfigurableOption `json:"configurable_options"`
	ConfiguredVariant   *CartItemProduct              `json:"configured_variant,omitempty"`
	CustomizableOptions []*SelectedCustomizableOption `json:"customizable_options"`
}

func (ConfigurableCartItem) IsCartItemInterface()              {}
func (this ConfigurableCartItem) GetUID() string               { return this.UID }
func (this ConfigurableCartItem) GetQuantity() float64         { return this.Quantity }
func (this ConfigurableCartItem) GetPrices() *CartItemPrices   { return this.Prices }
func (this ConfigurableCartItem) GetProduct() *CartItemProduct { return this.Product }
func (this ConfigurableCartItem) GetErrors() []*CartItemError {
	if this.Errors == nil {
		return nil
	}
	interfaceSlice := make([]*CartItemError, 0, len(this.Errors))
	for _, concrete := range this.Errors {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}

type ConfigurableProductCartItemInput struct {
	Data                *CartItemInput             `json:"data"`
	ParentSku           *string                    `json:"parent_sku,omitempty"`
	VariantSku          *string                    `json:"variant_sku,omitempty"`
	CustomizableOptions []*CustomizableOptionInput `json:"customizable_options,omitempty"`
}

type CreateGuestCartInput struct {
	CartUID *string `json:"cart_uid,omitempty"`
}

type CreateGuestCartOutput struct {
	Cart *Cart `json:"cart,omitempty"`
}

type CustomizableOptionInput struct {
	ID          *int   `json:"id,omitempty"`
	ValueString string `json:"value_string"`
}

type Discount struct {
	Amount    *Money                 `json:"amount"`
	Label     string                 `json:"label"`
	AppliedTo *DiscountAppliedToType `json:"applied_to,omitempty"`
}

type EnteredOptionInput struct {
	UID   string `json:"uid"`
	Value string `json:"value"`
}

type EstimateAddressInput struct {
	CountryCode string  `json:"country_code"`
	Region      *string `json:"region,omitempty"`
	RegionID    *int    `json:"region_id,omitempty"`
	Postcode    *string `json:"postcode,omitempty"`
}

type EstimateShippingMethodsInput struct {
	CartID  string                `json:"cart_id"`
	Address *EstimateAddressInput `json:"address"`
}

type EstimateTotalsInput struct {
	CartID         string                `json:"cart_id"`
	Address        *EstimateAddressInput `json:"address"`
	ShippingMethod *ShippingMethodInput  `json:"shipping_method,omitempty"`
}

type EstimateTotalsOutput struct {
	GrandTotal *Money `json:"grand_total,omitempty"`
	Subtotal   *Money `json:"subtotal,omitempty"`
	Tax        *Money `json:"tax,omitempty"`
	Shipping   *Money `json:"shipping,omitempty"`
	Discount   *Money `json:"discount,omitempty"`
}

type Money struct {
	Value    *float64      `json:"value,omitempty"`
	Currency *CurrencyEnum `json:"currency,omitempty"`
}

type Mutation struct {
}

type PaymentMethodInput struct {
	Code string `json:"code"`
}

type PlaceOrderError struct {
	Code    PlaceOrderErrorCodes `json:"code"`
	Message string               `json:"message"`
}

type PlaceOrderInput struct {
	CartID string `json:"cart_id"`
}

type PlaceOrderOutput struct {
	Errors  []*PlaceOrderError `json:"errors"`
	OrderV2 *PlacedOrder       `json:"orderV2,omitempty"`
}

type PlacedOrder struct {
	Number string `json:"number"`
	Token  string `json:"token"`
}

type Query struct {
}

type RemoveCouponFromCartInput struct {
	CartID string `json:"cart_id"`
}

type RemoveCouponFromCartOutput struct {
	Cart *Cart `json:"cart"`
}

type RemoveItemFromCartInput struct {
	CartID      string `json:"cart_id"`
	CartItemUID string `json:"cart_item_uid"`
}

type RemoveItemFromCartOutput struct {
	Cart *Cart `json:"cart"`
}

type ReorderItemsOutput struct {
	Cart            *Cart                     `json:"cart"`
	UserInputErrors []*CheckoutUserInputError `json:"userInputErrors"`
}

type SearchResultPageInfo struct {
	CurrentPage *int `json:"current_page,omitempty"`
	PageSize    *int `json:"page_size,omitempty"`
	TotalPages  *int `json:"total_pages,omitempty"`
}

type SelectedBundleOption struct {
	UID    string                       `json:"uid"`
	Label  string                       `json:"label"`
	Type   string                       `json:"type"`
	Values []*SelectedBundleOptionValue `json:"values"`
}

type SelectedBundleOptionValue struct {
	ID       int     `json:"id"`
	Label    string  `json:"label"`
	Quantity float64 `json:"quantity"`
	Price    float64 `json:"price"`
}

type SelectedConfigurableOption struct {
	ID          int    `json:"id"`
	OptionLabel string `json:"option_label"`
	ValueID     int    `json:"value_id"`
	ValueLabel  string `json:"value_label"`
}

type SelectedCustomizableOption struct {
	CustomizableOptionUID string                             `json:"customizable_option_uid"`
	ID                    int                                `json:"id"`
	IsRequired            bool                               `json:"is_required"`
	Label                 string                             `json:"label"`
	SortOrder             int                                `json:"sort_order"`
	Type                  string                             `json:"type"`
	Values                []*SelectedCustomizableOptionValue `json:"values"`
}

type SelectedCustomizableOptionValue struct {
	CustomizableOptionValueUID string                            `json:"customizable_option_value_uid"`
	ID                         int                               `json:"id"`
	Label                      string                            `json:"label"`
	Price                      *CartItemSelectedOptionValuePrice `json:"price"`
	Value                      string                            `json:"value"`
}

type SelectedPaymentMethod struct {
	Code  string  `json:"code"`
	Title *string `json:"title,omitempty"`
}

type SelectedShippingMethod struct {
	CarrierCode  string `json:"carrier_code"`
	CarrierTitle string `json:"carrier_title"`
	MethodCode   string `json:"method_code"`
	MethodTitle  string `json:"method_title"`
	Amount       *Money `json:"amount"`
	PriceExclTax *Money `json:"price_excl_tax"`
	PriceInclTax *Money `json:"price_incl_tax"`
}

type SetBillingAddressOnCartInput struct {
	CartID         string               `json:"cart_id"`
	BillingAddress *BillingAddressInput `json:"billing_address"`
}

type SetBillingAddressOnCartOutput struct {
	Cart *Cart `json:"cart"`
}

type SetGuestEmailOnCartInput struct {
	CartID string `json:"cart_id"`
	Email  string `json:"email"`
}

type SetGuestEmailOnCartOutput struct {
	Cart *Cart `json:"cart"`
}

type SetPaymentMethodOnCartInput struct {
	CartID        string              `json:"cart_id"`
	PaymentMethod *PaymentMethodInput `json:"payment_method"`
}

type SetPaymentMethodOnCartOutput struct {
	Cart *Cart `json:"cart"`
}

type SetShippingAddressesOnCartInput struct {
	CartID            string                  `json:"cart_id"`
	ShippingAddresses []*ShippingAddressInput `json:"shipping_addresses"`
}

type SetShippingAddressesOnCartOutput struct {
	Cart *Cart `json:"cart"`
}

type SetShippingMethodsOnCartInput struct {
	CartID          string                 `json:"cart_id"`
	ShippingMethods []*ShippingMethodInput `json:"shipping_methods"`
}

type SetShippingMethodsOnCartOutput struct {
	Cart *Cart `json:"cart"`
}

type ShippingAddressInput struct {
	Address           *CartAddressInput `json:"address,omitempty"`
	CustomerAddressID *int              `json:"customer_address_id,omitempty"`
}

type ShippingCartAddress struct {
	Firstname                string                     `json:"firstname"`
	Lastname                 string                     `json:"lastname"`
	Street                   []*string                  `json:"street"`
	City                     string                     `json:"city"`
	Region                   *CartAddressRegion         `json:"region,omitempty"`
	Postcode                 *string                    `json:"postcode,omitempty"`
	Country                  *CartAddressCountry        `json:"country"`
	Telephone                *string                    `json:"telephone,omitempty"`
	Company                  *string                    `json:"company,omitempty"`
	AvailableShippingMethods []*AvailableShippingMethod `json:"available_shipping_methods,omitempty"`
	SelectedShippingMethod   *SelectedShippingMethod    `json:"selected_shipping_method,omitempty"`
}

type ShippingMethodInput struct {
	CarrierCode string `json:"carrier_code"`
	MethodCode  string `json:"method_code"`
}

type SimpleCartItem struct {
	UID                 string                        `json:"uid"`
	Quantity            float64                       `json:"quantity"`
	Prices              *CartItemPrices               `json:"prices,omitempty"`
	Product             *CartItemProduct              `json:"product"`
	Errors              []*CartItemError              `json:"errors,omitempty"`
	CustomizableOptions []*SelectedCustomizableOption `json:"customizable_options"`
}

func (SimpleCartItem) IsCartItemInterface()              {}
func (this SimpleCartItem) GetUID() string               { return this.UID }
func (this SimpleCartItem) GetQuantity() float64         { return this.Quantity }
func (this SimpleCartItem) GetPrices() *CartItemPrices   { return this.Prices }
func (this SimpleCartItem) GetProduct() *CartItemProduct { return this.Product }
func (this SimpleCartItem) GetErrors() []*CartItemError {
	if this.Errors == nil {
		return nil
	}
	interfaceSlice := make([]*CartItemError, 0, len(this.Errors))
	for _, concrete := range this.Errors {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}

type SimpleProductCartItemInput struct {
	Data                *CartItemInput             `json:"data"`
	CustomizableOptions []*CustomizableOptionInput `json:"customizable_options,omitempty"`
}

type UpdateCartItemsInput struct {
	CartID    string                 `json:"cart_id"`
	CartItems []*CartItemUpdateInput `json:"cart_items"`
}

type UpdateCartItemsOutput struct {
	Cart *Cart `json:"cart"`
}

type VirtualProductCartItemInput struct {
	Data                *CartItemInput             `json:"data"`
	CustomizableOptions []*CustomizableOptionInput `json:"customizable_options,omitempty"`
}

type CreateEmptyCartInput struct {
	CartID *string `json:"cart_id,omitempty"`
}

type CartItemErrorType string

const (
	CartItemErrorTypeUndefined      CartItemErrorType = "UNDEFINED"
	CartItemErrorTypeItemQty        CartItemErrorType = "ITEM_QTY"
	CartItemErrorTypeItemIncrements CartItemErrorType = "ITEM_INCREMENTS"
)

var AllCartItemErrorType = []CartItemErrorType{
	CartItemErrorTypeUndefined,
	CartItemErrorTypeItemQty,
	CartItemErrorTypeItemIncrements,
}

func (e CartItemErrorType) IsValid() bool {
	switch e {
	case CartItemErrorTypeUndefined, CartItemErrorTypeItemQty, CartItemErrorTypeItemIncrements:
		return true
	}
	return false
}

func (e CartItemErrorType) String() string {
	return string(e)
}

func (e *CartItemErrorType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CartItemErrorType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CartItemErrorType", str)
	}
	return nil
}

func (e CartItemErrorType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CartItemErrorType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CartItemErrorType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CartUserInputErrorType string

const (
	CartUserInputErrorTypeProductNotFound   CartUserInputErrorType = "PRODUCT_NOT_FOUND"
	CartUserInputErrorTypeNotSalable        CartUserInputErrorType = "NOT_SALABLE"
	CartUserInputErrorTypeInsufficientStock CartUserInputErrorType = "INSUFFICIENT_STOCK"
	CartUserInputErrorTypeUndefined         CartUserInputErrorType = "UNDEFINED"
)

var AllCartUserInputErrorType = []CartUserInputErrorType{
	CartUserInputErrorTypeProductNotFound,
	CartUserInputErrorTypeNotSalable,
	CartUserInputErrorTypeInsufficientStock,
	CartUserInputErrorTypeUndefined,
}

func (e CartUserInputErrorType) IsValid() bool {
	switch e {
	case CartUserInputErrorTypeProductNotFound, CartUserInputErrorTypeNotSalable, CartUserInputErrorTypeInsufficientStock, CartUserInputErrorTypeUndefined:
		return true
	}
	return false
}

func (e CartUserInputErrorType) String() string {
	return string(e)
}

func (e *CartUserInputErrorType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CartUserInputErrorType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CartUserInputErrorType", str)
	}
	return nil
}

func (e CartUserInputErrorType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CartUserInputErrorType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CartUserInputErrorType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// How the checkout agreement acceptance is handled.
type CheckoutAgreementMode string

const (
	// Acceptance is recorded automatically.
	CheckoutAgreementModeAuto CheckoutAgreementMode = "AUTO"
	// The customer must manually check a checkbox.
	CheckoutAgreementModeManual CheckoutAgreementMode = "MANUAL"
)

var AllCheckoutAgreementMode = []CheckoutAgreementMode{
	CheckoutAgreementModeAuto,
	CheckoutAgreementModeManual,
}

func (e CheckoutAgreementMode) IsValid() bool {
	switch e {
	case CheckoutAgreementModeAuto, CheckoutAgreementModeManual:
		return true
	}
	return false
}

func (e CheckoutAgreementMode) String() string {
	return string(e)
}

func (e *CheckoutAgreementMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CheckoutAgreementMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CheckoutAgreementMode", str)
	}
	return nil
}

func (e CheckoutAgreementMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CheckoutAgreementMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CheckoutAgreementMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CheckoutUserInputErrorCodes string

const (
	CheckoutUserInputErrorCodesReorderNotAvailable CheckoutUserInputErrorCodes = "REORDER_NOT_AVAILABLE"
	CheckoutUserInputErrorCodesProductNotFound     CheckoutUserInputErrorCodes = "PRODUCT_NOT_FOUND"
	CheckoutUserInputErrorCodesNotSalable          CheckoutUserInputErrorCodes = "NOT_SALABLE"
	CheckoutUserInputErrorCodesInsufficientStock   CheckoutUserInputErrorCodes = "INSUFFICIENT_STOCK"
	CheckoutUserInputErrorCodesUndefined           CheckoutUserInputErrorCodes = "UNDEFINED"
)

var AllCheckoutUserInputErrorCodes = []CheckoutUserInputErrorCodes{
	CheckoutUserInputErrorCodesReorderNotAvailable,
	CheckoutUserInputErrorCodesProductNotFound,
	CheckoutUserInputErrorCodesNotSalable,
	CheckoutUserInputErrorCodesInsufficientStock,
	CheckoutUserInputErrorCodesUndefined,
}

func (e CheckoutUserInputErrorCodes) IsValid() bool {
	switch e {
	case CheckoutUserInputErrorCodesReorderNotAvailable, CheckoutUserInputErrorCodesProductNotFound, CheckoutUserInputErrorCodesNotSalable, CheckoutUserInputErrorCodesInsufficientStock, CheckoutUserInputErrorCodesUndefined:
		return true
	}
	return false
}

func (e CheckoutUserInputErrorCodes) String() string {
	return string(e)
}

func (e *CheckoutUserInputErrorCodes) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CheckoutUserInputErrorCodes(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CheckoutUserInputErrorCodes", str)
	}
	return nil
}

func (e CheckoutUserInputErrorCodes) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CheckoutUserInputErrorCodes) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CheckoutUserInputErrorCodes) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CurrencyEnum string

const (
	CurrencyEnumUsd CurrencyEnum = "USD"
	CurrencyEnumEur CurrencyEnum = "EUR"
	CurrencyEnumGbp CurrencyEnum = "GBP"
	CurrencyEnumCad CurrencyEnum = "CAD"
	CurrencyEnumAud CurrencyEnum = "AUD"
	CurrencyEnumJpy CurrencyEnum = "JPY"
	CurrencyEnumCny CurrencyEnum = "CNY"
	CurrencyEnumChf CurrencyEnum = "CHF"
	CurrencyEnumSek CurrencyEnum = "SEK"
	CurrencyEnumNok CurrencyEnum = "NOK"
	CurrencyEnumDkk CurrencyEnum = "DKK"
	CurrencyEnumNzd CurrencyEnum = "NZD"
	CurrencyEnumMxn CurrencyEnum = "MXN"
	CurrencyEnumSgd CurrencyEnum = "SGD"
	CurrencyEnumHkd CurrencyEnum = "HKD"
	CurrencyEnumInr CurrencyEnum = "INR"
	CurrencyEnumBrl CurrencyEnum = "BRL"
	CurrencyEnumZar CurrencyEnum = "ZAR"
	CurrencyEnumRub CurrencyEnum = "RUB"
	CurrencyEnumKrw CurrencyEnum = "KRW"
	CurrencyEnumTry CurrencyEnum = "TRY"
	CurrencyEnumPln CurrencyEnum = "PLN"
	CurrencyEnumCzk CurrencyEnum = "CZK"
	CurrencyEnumHuf CurrencyEnum = "HUF"
	CurrencyEnumRon CurrencyEnum = "RON"
	CurrencyEnumBgn CurrencyEnum = "BGN"
	CurrencyEnumHrk CurrencyEnum = "HRK"
	CurrencyEnumIls CurrencyEnum = "ILS"
	CurrencyEnumPhp CurrencyEnum = "PHP"
	CurrencyEnumThb CurrencyEnum = "THB"
	CurrencyEnumMyr CurrencyEnum = "MYR"
	CurrencyEnumIDR CurrencyEnum = "IDR"
	CurrencyEnumAed CurrencyEnum = "AED"
	CurrencyEnumSar CurrencyEnum = "SAR"
	CurrencyEnumQar CurrencyEnum = "QAR"
	CurrencyEnumKwd CurrencyEnum = "KWD"
	CurrencyEnumBhd CurrencyEnum = "BHD"
	CurrencyEnumOmr CurrencyEnum = "OMR"
	CurrencyEnumJod CurrencyEnum = "JOD"
	CurrencyEnumLbp CurrencyEnum = "LBP"
	CurrencyEnumEgp CurrencyEnum = "EGP"
	CurrencyEnumMad CurrencyEnum = "MAD"
	CurrencyEnumTnd CurrencyEnum = "TND"
	CurrencyEnumDzd CurrencyEnum = "DZD"
)

var AllCurrencyEnum = []CurrencyEnum{
	CurrencyEnumUsd,
	CurrencyEnumEur,
	CurrencyEnumGbp,
	CurrencyEnumCad,
	CurrencyEnumAud,
	CurrencyEnumJpy,
	CurrencyEnumCny,
	CurrencyEnumChf,
	CurrencyEnumSek,
	CurrencyEnumNok,
	CurrencyEnumDkk,
	CurrencyEnumNzd,
	CurrencyEnumMxn,
	CurrencyEnumSgd,
	CurrencyEnumHkd,
	CurrencyEnumInr,
	CurrencyEnumBrl,
	CurrencyEnumZar,
	CurrencyEnumRub,
	CurrencyEnumKrw,
	CurrencyEnumTry,
	CurrencyEnumPln,
	CurrencyEnumCzk,
	CurrencyEnumHuf,
	CurrencyEnumRon,
	CurrencyEnumBgn,
	CurrencyEnumHrk,
	CurrencyEnumIls,
	CurrencyEnumPhp,
	CurrencyEnumThb,
	CurrencyEnumMyr,
	CurrencyEnumIDR,
	CurrencyEnumAed,
	CurrencyEnumSar,
	CurrencyEnumQar,
	CurrencyEnumKwd,
	CurrencyEnumBhd,
	CurrencyEnumOmr,
	CurrencyEnumJod,
	CurrencyEnumLbp,
	CurrencyEnumEgp,
	CurrencyEnumMad,
	CurrencyEnumTnd,
	CurrencyEnumDzd,
}

func (e CurrencyEnum) IsValid() bool {
	switch e {
	case CurrencyEnumUsd, CurrencyEnumEur, CurrencyEnumGbp, CurrencyEnumCad, CurrencyEnumAud, CurrencyEnumJpy, CurrencyEnumCny, CurrencyEnumChf, CurrencyEnumSek, CurrencyEnumNok, CurrencyEnumDkk, CurrencyEnumNzd, CurrencyEnumMxn, CurrencyEnumSgd, CurrencyEnumHkd, CurrencyEnumInr, CurrencyEnumBrl, CurrencyEnumZar, CurrencyEnumRub, CurrencyEnumKrw, CurrencyEnumTry, CurrencyEnumPln, CurrencyEnumCzk, CurrencyEnumHuf, CurrencyEnumRon, CurrencyEnumBgn, CurrencyEnumHrk, CurrencyEnumIls, CurrencyEnumPhp, CurrencyEnumThb, CurrencyEnumMyr, CurrencyEnumIDR, CurrencyEnumAed, CurrencyEnumSar, CurrencyEnumQar, CurrencyEnumKwd, CurrencyEnumBhd, CurrencyEnumOmr, CurrencyEnumJod, CurrencyEnumLbp, CurrencyEnumEgp, CurrencyEnumMad, CurrencyEnumTnd, CurrencyEnumDzd:
		return true
	}
	return false
}

func (e CurrencyEnum) String() string {
	return string(e)
}

func (e *CurrencyEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CurrencyEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CurrencyEnum", str)
	}
	return nil
}

func (e CurrencyEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CurrencyEnum) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CurrencyEnum) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DiscountAppliedToType string

const (
	DiscountAppliedToTypeItem      DiscountAppliedToType = "ITEM"
	DiscountAppliedToTypeShipping  DiscountAppliedToType = "SHIPPING"
	DiscountAppliedToTypeWholeCart DiscountAppliedToType = "WHOLE_CART"
)

var AllDiscountAppliedToType = []DiscountAppliedToType{
	DiscountAppliedToTypeItem,
	DiscountAppliedToTypeShipping,
	DiscountAppliedToTypeWholeCart,
}

func (e DiscountAppliedToType) IsValid() bool {
	switch e {
	case DiscountAppliedToTypeItem, DiscountAppliedToTypeShipping, DiscountAppliedToTypeWholeCart:
		return true
	}
	return false
}

func (e DiscountAppliedToType) String() string {
	return string(e)
}

func (e *DiscountAppliedToType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiscountAppliedToType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiscountAppliedToType", str)
	}
	return nil
}

func (e DiscountAppliedToType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DiscountAppliedToType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DiscountAppliedToType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlaceOrderErrorCodes string

const (
	PlaceOrderErrorCodesCartNotFound       PlaceOrderErrorCodes = "CART_NOT_FOUND"
	PlaceOrderErrorCodesCartNotActive      PlaceOrderErrorCodes = "CART_NOT_ACTIVE"
	PlaceOrderErrorCodesGuestEmailMissing  PlaceOrderErrorCodes = "GUEST_EMAIL_MISSING"
	PlaceOrderErrorCodesUnableToPlaceOrder PlaceOrderErrorCodes = "UNABLE_TO_PLACE_ORDER"
	PlaceOrderErrorCodesUndefined          PlaceOrderErrorCodes = "UNDEFINED"
)

var AllPlaceOrderErrorCodes = []PlaceOrderErrorCodes{
	PlaceOrderErrorCodesCartNotFound,
	PlaceOrderErrorCodesCartNotActive,
	PlaceOrderErrorCodesGuestEmailMissing,
	PlaceOrderErrorCodesUnableToPlaceOrder,
	PlaceOrderErrorCodesUndefined,
}

func (e PlaceOrderErrorCodes) IsValid() bool {
	switch e {
	case PlaceOrderErrorCodesCartNotFound, PlaceOrderErrorCodesCartNotActive, PlaceOrderErrorCodesGuestEmailMissing, PlaceOrderErrorCodesUnableToPlaceOrder, PlaceOrderErrorCodesUndefined:
		return true
	}
	return false
}

func (e PlaceOrderErrorCodes) String() string {
	return string(e)
}

func (e *PlaceOrderErrorCodes) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlaceOrderErrorCodes(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlaceOrderErrorCodes", str)
	}
	return nil
}

func (e PlaceOrderErrorCodes) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlaceOrderErrorCodes) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlaceOrderErrorCodes) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PriceTypeEnum string

const (
	PriceTypeEnumFixed   PriceTypeEnum = "FIXED"
	PriceTypeEnumPercent PriceTypeEnum = "PERCENT"
	PriceTypeEnumDynamic PriceTypeEnum = "DYNAMIC"
)

var AllPriceTypeEnum = []PriceTypeEnum{
	PriceTypeEnumFixed,
	PriceTypeEnumPercent,
	PriceTypeEnumDynamic,
}

func (e PriceTypeEnum) IsValid() bool {
	switch e {
	case PriceTypeEnumFixed, PriceTypeEnumPercent, PriceTypeEnumDynamic:
		return true
	}
	return false
}

func (e PriceTypeEnum) String() string {
	return string(e)
}

func (e *PriceTypeEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PriceTypeEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PriceTypeEnum", str)
	}
	return nil
}

func (e PriceTypeEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PriceTypeEnum) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PriceTypeEnum) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
